### ISSUE TITLE
构造函数异常引发的崩溃

### ISSUE THREAD

**Issue by StrollStars** [KaiHuaDou/EasyBrowserAdvanced#1]
Win7 32位和64位，启动都报如下错误：
> 对类型“极简浏览器.MainWindow”的构造函数执行符合指定的绑定约束的调用时引发了异常。

不支持Win7？已安装更新版本的.Net Framework。

**Comment by KaiHuaDou** [comment]
很抱歉出现了这个错误。理论上，这个浏览器支持Win7及其以上的所有版本。
我很激动，您是第一个对我的浏览器做出反馈的人。


根据我以往的经验，这个问题应该出在构造函数上。
在我们家另一台32位Win7上，没有出现任何问题。
您收到这封邮件时，问题应该已经被修复了，但是也希望您可以检查以下几点：
1.是否给予浏览器足够的权限
1.如果您是下载源代码并编译运行的话，建议您切换到正式发布版本；
2.Chrome 85+可否在电脑上正常运行；
3.您的运行时环境（.Net Framework 4.5.2）是否正常。
有任何问题，欢迎您随时联系我。
谢谢！


KaiHuaDou
2021.6.2

**Comment by KaiHuaDou** [comment]
希望您可以把log文件夹下的三个log文件文件发过来
如果我没有判断错，您的错误提示框会有如下样式
1.标题为“极简浏览器”
2.只有一个“确定”按钮
3.有一个红色的叹号图标

**Comment by StrollStars** [comment]
@KaiHuaDou 谢谢回复，我是想找个精简免安装的Chrome找到了您的产品。

1.浏览器的权限应该是够了，只有一个防火墙，但不影响启动。
2.我是直接下载了[Releases](https://github.com/KaiHuaDou/EasyBrowserAdvanced/releases)里的压缩包解压后运行的。
3.下载了最新版本91，可以正常运行，防火墙弹出询问窗口。
4.日志文件夹中只有2个文件，其中一个还是空文件。附件：[log.zip](https://github.com/KaiHuaDou/EasyBrowserAdvanced/files/6602261/log.zip)
5.错误样式前两点都对，只是第三点是个红色的叉，如图。
![2021-06-05_170453](https://user-images.githubusercontent.com/10942225/120886348-16e08c80-c620-11eb-82a7-cbc460c3ae0a.jpg)

**Comment by KaiHuaDou** [comment]
错误已修正，您可以在最新发布的版本看到。运行时您有可能看到“文明语言检测器启动失败，单击确定以继续使用。”的字样
[发布地址](https://github.com/KaiHuaDou/EasyBrowserAdvanced/releases/tag/v3.3.1.11)

**Comment by StrollStars** [comment]
@KaiHuaDou 没有了“构造函数异常”的报错窗口，但还是报错无法启动。[log.zip](https://github.com/KaiHuaDou/EasyBrowserAdvanced/files/6643441/log.zip)

**Comment by KaiHuaDou** [comment]
确保应用程序与图片里的所有文件处在同一目录下![image](https://user-images.githubusercontent.com/74781268/148385537-5fcefbf7-3302-42d5-ac18-8ca375ac1644.png)

**Comment by StrollStars** [comment]
直接解压运行，应该没有缺少文件，Win10没有问题。

**Comment by KaiHuaDou** [comment]
既然Win10没有问题，那可以检查一下Win7比Win10少了哪些依赖项，安装上应该就没问题了。

**Comment by KaiHuaDou** [comment]
您也可以查看一下我应用程序的配置（查看我的源代码），检查一下有没有那些问题，提交一个Pull Request或在此issue里告诉我。

**Comment by StrollStars** [comment]
@KaiHuaDou 是缺了[Visual Studio 2015、2017、2019 和 2022可再发行程序包](https://docs.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist)，安装之后就能正常运行了，谢谢多次帮助。
