### ISSUE TITLE
你好，下载好，怎么使用啊，没有找到. exe

### ISSUE THREAD

**Issue by GUI9527** [KaiHuaDou/EasyBrowserAdvanced#2]
没有.exe启动程序吗？？

**Comment by KaiHuaDou** [comment]
去Release里下载，
解压压缩包，就能找到"极简浏览器.exe"

**Comment by GUI9527** [comment]
ok,非常感谢！

**Comment by GUI9527** [comment]
这个追求极简的，定义各种快捷键留给使用者自行定义吧？谷歌浏览器快捷键把F1到F12都快给用完了，真恼火还不可以重新定义或关闭这些快捷键，呵呵
