### ISSUE TITLE
浏览器无法播放视频

### ISSUE THREAD

**Issue by KaiHuaDou** [KaiHuaDou/EasyBrowserAdvanced#3]
测试时发现无法播放视频后来找到了是chromium不将H.264开源，百度上的解决方案都是替换nuget包，但是这样就不便于升级内核版本，如果自己修改编译耗时又过长，实在是左右为难，希望有大神帮助！

**Comment by KaiHuaDou** [comment]
有没有将视频播放器嵌入网页的方案？或者改用Gecko内核？

**Comment by zhaojunliing** [comment]
求解决方法
