### ISSUE TITLE
无法播放视频这个问题，现在还无解吗

### ISSUE THREAD

**Issue by alex1997cheer** [KaiHuaDou/EasyBrowserAdvanced#8]

**Comment by KaiHuaDou** [comment]
有解决方法：重新编译 Chromium 87 + CefSharp 87。但是这个工程量太大。

**Comment by zhaojunliing** [comment]
https://github.com/winsoft666/cef_binary/tree/master

这个项目有编译好的89版本，能直接用不

**Comment by KaiHuaDou** [comment]
我试一试，最近正在备考。

**Comment by KaiHuaDou** [comment]
最新 commit，在我的电脑上能用：ce711d8d76776b5923fe2d9b5a91a218ff59449e

**Comment by KaiHuaDou** [comment]
#9 关闭 Issue
